# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatientPortalUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PatientPortalUI.PatientRecord'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='date_of_visit',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='visit',
            name='record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PatientPortalUI.PatientRecord'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_name',
            field=models.CharField(default='Ibuprofen', max_length=200),
        ),
    ]
