# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortalUI', '0002_auto_20170318_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(default=b"5'7", max_length=200)),
                ('temp', models.DecimalField(decimal_places=1, default=98.7, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=1, default=180, max_digits=5)),
                ('systolic', models.DecimalField(decimal_places=0, default=120, max_digits=3)),
                ('diastolic', models.DecimalField(decimal_places=0, default=80, max_digits=3)),
            ],
        ),
    ]
